on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: ensuring commit message is byte
        run: |
          #!/bin/bash
          set -euo pipefail ; IFS=$'\n\t'
          message=$(git log --format=%B -n 1 ${{ github.event.after }})
          echo "message: ${message}"
          echo "${message}" | grep "^byte$" &>/dev/null;
  smoke-unix:
    needs: commit-lint
    strategy:
      matrix:
        os: [
        ubuntu-latest,
        # macos-11
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: "debug info"
        run: |
          echo "uname -a" ;  uname -a
          echo "env" ; env
          echo "pwd" ; pwd
          echo "ls -la" ; ls -la
      - name: "make-usan"
        run:  |
          make clean
          make CLANG_USAN=1
      - name: "run"
        run: |
          ./bytey | grep nom
          file ./bytey
      - name: "make-asan"
        run:  |
          make clean
          make CLANG_ASAN=1
      - name: "run"
        run: |
          ./bytey | grep nom
          file ./bytey
      - name: "make-msan"
        run:  |
          make clean
          make CLANG_MSAN=1
      - name: "run"
        run: |
          ./bytey | grep nom
          file ./bytey
      - name: "make"
        run:  |
          make clean
          make
      - name: "run"
        run: |
          file ./bytey          
          ./bytey | grep nom
  smoke-windows:
    needs: commit-lint
    strategy:
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: "debug info"
        run: |
          echo "uname -a" ; uname -a
          echo "env" ; env
          echo "pwd" ; pwd
          echo "dir" ; dir
      - run: make
      - run: file ./bytey.exe
      - run: ./bytey.exe | grep nom
